### ISSUE TITLE
Use `an` before `1x`, not `a`

### ISSUE THREAD

**Issue by katydecorah** [retextjs/retext-indefinite-article#11]
Similar to #5 and #7, I received the following warning:

```
1:14-1:15  warning  Use `an` before `1x`, not `a`   retext-indefinite-article  retext-indefinite-article
```

I expected "a 1x" to be correct. If you agree, I'd be happy to create a PR.

**Comment by Murderlon** [comment]
Good catch. I believe you are correct and happy to take a PR.

You can check this commit to see how a previous exception for "1" was implemented: https://github.com/retextjs/retext-indefinite-article/commit/2fc613a641349a45ba02ad1459eafde8a95a4914
