### ISSUE TITLE
Does Not Account for Markdown Styling Correctly

### ISSUE THREAD

**Issue by Zamiell** [retextjs/retext-indefinite-article#14]
In my "README.md" file (a markdown file), `retext-indefine-article` will successfully throw a warning for the following mistakes:

```
I bit into a apple.
I bit into a [apple](https://www.apple.com).
```

But it will fail to catch the following mistakes:

```
I bit into a *apple*.
I bit into a **apple**.
```

Is this a bug in `retext-indefine-article`, or is there some additional processing step that I am supposed to add to the pipeline?
(I did try adding in a `remark-parse` into my pipeline for fun, but the bug was still present.)

**Comment by ChristianMurphy** [comment]
@Zamiell please follow the issue templates, they exist to gather the information needed to resolve issues.
If you believe this is an issue, please fill in: https://github.com/retextjs/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug.md
If this is a question, as:
> is there some additional processing step that I am supposed to add to the pipeline?

implies, please move this to https://spectrum.chat/unified/retext
as https://github.com/retextjs/.github/blob/main/.github/ISSUE_TEMPLATE/3-help.md recommends

**Comment by Zamiell** [comment]
@ChristianMurphy My apologies, here's the issue template:

Subject of the issue: See original post.
My environment:
  * OS: Windows 10
  * Packages:
    * retext-repeated-words v3.0.0
    * retext v7.0.1
    * retext-english v3.0.4
  * Env:
    * npm v6.13.4
    * node v12.13.0

Steps to reproduce: See original post.
Expected behavior: The linter should catch `I bit into a *apple*.`.
Actual behavior: The linter does not catch `I bit into a *apple*.`.

Let me know if I missed any information.

**Comment by ChristianMurphy** [comment]
Thanks @Zamiell!
How are you running `retext-indefinite-article`?
Could you share the `.retextrc` config or `unified` pipeline?

**Comment by Zamiell** [comment]
I am running it exactly like it is specified in the readme.md file, e.g.:

test.js
```
var vfile = require('to-vfile')
var report = require('vfile-reporter')
var unified = require('unified')
var english = require('retext-english')
var stringify = require('retext-stringify')
var indefiniteArticle = require('retext-indefinite-article')

unified()
  .use(english)
  .use(indefiniteArticle)
  .use(stringify)
  .process(vfile.readSync('example.txt'), function(err, file) {
    console.error(report(err || file))
  })
```

example.txt
```
He should, a *8-year* old boy, should have arrived a hour
ago on an European flight.  An historic event, or a
historic event? Both are fine.
```

**Comment by ChristianMurphy** [comment]
@Zamiell retext is just for plain text, it isn't markdown aware.
If you want to account for markdown styling use https://github.com/remarkjs/remark-retext

**Comment by Zamiell** [comment]
Thanks for the tip. For future reference, this is the modified example that will successfully parse the italicized/bolded text:

```
var vfile = require('to-vfile')
var report = require('vfile-reporter')
var unified = require('unified')
var parse = require('remark-parse')
var remark2retext = require('remark-retext')
var english = require('retext-english')
var indefiniteArticle = require('retext-indefinite-article')
var stringify = require('retext-stringify')

unified()
  .use(parse)
  .use(
    remark2retext,
    unified()
      .use(english)
      .use(indefiniteArticle)
  )
  .use(stringify)
  .process(vfile.readSync('example.txt'), function(err, file) {
    console.error(report(err || file))
  })
```

Can we add this example to the readme.md?

As an aside, why is `retext-indefinite-article` able to parse markdown links as raw text? It is confusing for the end-user, because it gives the appearance that the library is able to parse markdown text correctly. Is this a bug? I would expect a parenthesis or bracket to count as a word boundary.

**Comment by wooorm** [comment]
@Zamiell Hi there! From what I read, you are currently confused about what this project is, what retext is, what remark does.

This module is one of 400+ projects. And they all exist around unified. Yes, that’s a lot. It’s also very powerful! I suggest taking a couple of hours to read up on that: https://unifiedjs.com (there’s a learn section with useful guides). And then, if you have more questions, please ask them on Spectrum!

All these things you are asking can be done with unified, and it looks like you’re already well on your way! ✨

---

For this issue: this project does not deal with markdown. And it doesn’t say it does. There are other unified projects that do so, as @ChristianMurphy mentioned: remark does markdown, and remark-retext is the bridge between markdown and natural language.

**Comment by Zamiell** [comment]
wooorm, thanks for the replay. Regarding the example, don't you think it would be valuable to add it to the readme.md file? I would imagine that using `retext-indefinite-article` with markdown is a common use-case. Consider that this is the repository that people will land on from google when searching for "lint my markdown document indefinite articles".

**Comment by wooorm** [comment]
All these 400 projects will work in combination with each other: that means that there are bazillions of examples needed to cover all cases. Hence, we choose to include a single common case example in each readme that covers that project.

In fact, I’m assuming you already feel a bit overwhelmed, clicking on the links in this project and retext’s readme, right? I don’t think adding *more* information will help.

> Consider that this is the repository that people will land on from google when searching for "lint my markdown document indefinite articles".

That is outside our control: this project does not mention markdown. However, lucky you: you can do it ;)

**Comment by Zamiell** [comment]
Ok, that's completely reasonable. I'm all set - thanks for the quick reply and your work on this library.

**Comment by wooorm** [comment]
Thanks, also: Hi, you are welcome here! 👋 I hope unified helps, that you’ll like it, and that you can do cool things with it!
