### ISSUE TITLE
Suggests "a h1" though the HTML specification uses "an h1"

### ISSUE THREAD

**Issue by DavidAnson** [retextjs/retext-indefinite-article#15]
### Subject of the issue

`retext-indefinite-article` suggests using "a h1" although the HTML specification uses "an h1" throughout. Because "h1" is pronounced "ach one", "a ach one" seems to violate the "'a' for consonant sounds" rule for indefinite articles.

### Your environment

*   **OS**: macOS 11.3
*   **Packages**: spellchecker-cli@4.4.0, uses retext-indefinite-article@1.1.7
*   **Env**: Node 14

### Steps to reproduce

```bash
user@host anh1 % node --version
v14.15.4
user@host anh1 % npm install spellchecker-cli --no-package-lock
+ spellchecker-cli@4.4.0
user@host anh1 % cat text.md 
A header element is intended to usually contain the section's heading (an h1–h6 element or an hgroup element), but this is not required. The header element can also be used to wrap a section's table of contents, a search form, or any relevant logos.

user@host anh1 % ./node_modules/.bin/spellchecker text.md 

Spellchecking 1 file...

text.md
   1:72-1:74  warning  Use `a` before `h1`, not `an`                                                                         retext-indefinite-article  retext-indefinite-article
...

⚠ 5 warnings
user@host anh1 % npm ls retext-indefinite-article
/Users/user/anh1
└─┬ spellchecker-cli@4.4.0
  └── retext-indefinite-article@1.1.7 
```

### Expected behavior

The sample text above is taken directly from https://html.spec.whatwg.org/multipage/sections.html#the-header-element and is presumably correct as written. See also the first section of this issue.

### Actual behavior

Correction is suggested.

**Comment by wooorm** [comment]
:+1:

I don’t think this can be a general rule, as one could argue that `h8` should be pronounced “`height`” or `hate”, so I’ll add some exceptions for h1-6.

**Comment by wooorm** [comment]
[Released](https://github.com/retextjs/retext-indefinite-article/releases/tag/2.0.2)!
