### ISSUE TITLE
Use `an` before `unicycle`, not `a`

### ISSUE THREAD

**Issue by charleskorn** [retextjs/retext-indefinite-article#16]
### Subject of the issue

Similar to #9 - "unicycle" starts with a "Y" sound when pronounced, so should use "a", not "an"

### Your environment

*   **OS**: macOS 10.15
*   **Packages**: `retext-indefinite-article` 2.0.2
*   **Env**: Node 15.10.0, Yarn 1.22.10

### Steps to reproduce

1. Create a document with "a unicycle" in the text.
1. Run retext-indefinite-article on document.

### Expected behavior

No warnings emitted.

### Actual behavior

Warning emitted:
```
Use `an` before `unicycle`, not `a`
```

**Comment by wooorm** [comment]
Nice! thanks!

Would you be willing to work on a PR?

**Comment by binyamin** [comment]
@wooorm also "unist" :grinning:

**Comment by binyamin** [comment]
Also "unist" :grinning:

**Comment by wooorm** [comment]
good idea, added, thanks!
