### ISSUE TITLE
`an` expected before `1/4`

### ISSUE THREAD

**Issue by benbalter** [retextjs/retext-indefinite-article#5]
When I run retext-indefinite-article against a document with the phrase `a 1/4" hole`, I get the following:

```
13:17-13:18  warning  Use `an` before `1/4`, not `a`                             retext-indefinite-article   retext-indefinite-article
```

In my mind 1/4 should be preceded by "a", not "an". If it's read as "quarter", it's clearly an "a". If it's read as "one-quarter", it should still be "a" since "one" starts with a "w" sound.

Testing locally, number to words is returning "one" when given the input `"1/4"` and "zero" when given the input `1/4`.

**Comment by wooorm** [comment]
Interesting!
I’m doing some research, and am not entirely sure yet, but here’s the first I found: https://english.stackexchange.com/questions/314316/can-you-use-a-before-1-4-when-there-is-no-unit-following

**Comment by wooorm** [comment]
Ah, there wasn’t any handling of words that start with `1`!
Thanks for finding this, and let me know if you find more!
