### ISSUE TITLE
`an` expected before `union`

### ISSUE THREAD

**Issue by raipc** [retextjs/retext-indefinite-article#9]
"Union" starts with a "Y" sound when pronounced, hence should be "a", not "an".

**Comment by wooorm** [comment]
Thanks. Could you provide an example case next time?

**Comment by raipc** [comment]
Thank you for fast response, I will provide examples. 
I found that many tools including this one misclassify articles in abbreviations, e.g. `an SQL query` or `an nmon file`. Have you thought about preprocessing some corpora to find typical use-cases? The [Articles](https://github.com/chadkirby/Articles) library is told to be based on Wikipedia corpus (though, the examples above are misclassified, too)

**Comment by wooorm** [comment]
That’s very smart! Something like that would be amazing!

Would you be into working on that?

**Comment by raipc** [comment]
I wish I had enough javascript and language processing skills. Maybe it's possible to fork the project and use it here? I believe the trie can be simplified (the trie contains some errors which are easy to find), but the additional trie modification would be hard. Probably it's worth writing a tool that receives a map of words to articles and returns the modified trie.
